<a href="https://colab.research.google.com/github/loolzaaa/faster-rcnn-pytorch/blob/master/Faster_RCNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip uninstall torch torchvision -y
!pip install colorama easydict pyyaml matplotlib numpy
!pip install torch==1.4.0+cu100 torchvision==0.5.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html

In [ ]:
!git clone https://github.com/loolzaaa/faster-rcnn-pytorch.git

In [ ]:
%cd faster-rcnn-pytorch
!mkdir data
!mkdir data/pretrained_model
%cd lib

!python setup.py develop

%cd ..

In [ ]:
import lib # Add some path to sys
import torch # You need to import this first
import _C

print(_C)

In [ ]:
!wget -O data/voc2007.tar http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtrainval_06-Nov-2007.tar
!tar -xf data/voc2007.tar -C data/

!wget -O data/pretrained_model/resnet50.pth "https://drive.google.com/uc?export=download&id=1Wv-j1qtRsYWcuCVakuaN0kXV6ZcQ3yzK"

In [3]:
%matplotlib inline
# Before run, check script/train.py file.
# You need to change pprint.pp -> pprint.pprint,
# because pp() function available in python 3.8+
!python3.8 run.py train -n resnet101 --cuda

Called with args:
Namespace(add_params=[], batch_size=None, class_agnostic=False, cuda=True, dataset='voc_2007_trainval', display_interval=100, epoch=1, learning_rate=None, lr_decay_gamma=None, lr_decay_step=None, mGPU=False, mode='train', net='resnet101', optimizer='sgd', pretrain=False, resume=False, save_dir='models', session=1, total_epoch=20, vis_off=False)
Current device: CUDA:0
Using config:
GENERAL:
{'MAX_IMG_RATIO': 2.0,
 'MAX_IMG_SIZE': 1000,
 'MIN_IMG_RATIO': 0.5,
 'MIN_IMG_SIZE': 600,
 'POOLING_MODE': 'pool',
 'POOLING_SIZE': 7}
TRAIN:
{'BATCH_SIZE': 1,
 'BG_THRESHOLD_HI': 0.5,
 'BG_THRESHOLD_LO': 0.0,
 'BIAS_DECAY': False,
 'DOUBLE_BIAS': True,
 'FG_PROPOSAL_FRACTION': 0.25,
 'FG_THRESHOLD': 0.5,
 'LEARNING_RATE': 0.001,
 'LR_DECAY_GAMMA': 0.1,
 'LR_DECAY_STEP': 5,
 'MOMENTUM': 0.9,
 'PROPOSAL_PER_IMG': 256,
 'RPN_CLOBBER_POSITIVES': False,
 'RPN_FG_LABELS_FRACTION': 0.5,
 'RPN_MAX_LABELS': 256,
 'RPN_NEGATIVE_OVERLAP': 0.3,
 'RPN_NMS_THRESHOLD': 0.7,
 'RPN_POSITIVE_OVERLA

In [1]:
!pwd

/root/faster-rcnn-pytorch


In [16]:
import numpy as np
a = np.array([[ -34,63,280, 257],
 [224,  72, 632, -370]])

In [17]:
a

array([[ -34,   63,  280,  257],
       [ 224,   72,  632, -370]])

In [21]:
np.array([a[0,:],a[0,:]])

array([[-34,  63, 280, 257],
       [-34,  63, 280, 257]])

In [36]:
b = np.array([])
print(a)
for i in range(a.shape[0]):
    row = a[i,:]
#     print(row)
    row[0] = row[0]+1
#     print(row)
    a[i,:] = row
a

[[ -33   63  280  257]
 [ 225   72  632 -370]]


array([[ -32,   63,  280,  257],
       [ 226,   72,  632, -370]])

In [40]:
t = np.array([-0.3, -45.234])
t

array([ -0.3  , -45.234])

In [41]:
for i in range(t.shape[1]):
    t[i] = int(t[i])

IndexError: tuple index out of range

In [42]:
t.shape

(2,)

In [43]:
t[0]

-0.3

In [47]:
t = t.reshape((1,2))

In [48]:
t.shape

(1, 2)

In [49]:
t[0]

array([ -0.3  , -45.234])

In [50]:
t[0][0]

-0.3